// <auto-generated />
namespace Events.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CheckIn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CheckIn));
        
        string IMigrationMetadata.Id
        {
            get { return "202111170516411_CheckIn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
